name: Add checksums to releases

on: [release, workflow_dispatch]

defaults:
  run:
    shell: pwsh

jobs:
  job:
    runs-on: windows-latest
    steps:
      - uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: "*.exe"
          tarBall: false
          zipBall: false
      - name: Create checksum files
        run: |
          Get-ChildItem -Filter "*.exe" | ForEach-Object {
            $hash = (Get-FileHash $_.FullName -Algorithm SHA256).Hash
            Set-Content -Path "$($_.FullName).sha256" -Value $hash
          }
      - name: Upload checksum files
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "*.sha256"
          update_latest_release: true
