name: Add checksums to releases

on: [release, workflow_dispatch]

defaults:
  run:
    shell: pwsh

jobs:
  job:
    runs-on: windows-latest
    steps:
      - uses: robinraju/release-downloader@v1
        with:
          latest: true
          fileName: "*.exe"
          tarBall: false
          zipBall: false
      - name: List files (test)
        run: ls
